// <auto-generated />
namespace BitfinexCharter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class Adding5minCandles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adding5minCandles));
        
        string IMigrationMetadata.Id
        {
            get { return "201708180603150_Adding5minCandles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
